# Use an official Node.js runtime as a parent image
FROM node:18.17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the entire React app source code into the container
COPY . .

# Build the React app (you can customize this for your specific build process)
RUN npm run build

# Expose the port your React app will run on
EXPOSE 5173
# Define the command to start your React app (adjust this as needed)
CMD ["npm", "start"]
